name: Deploy to Homelab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Connect and deploy via SSH (Cloudflare Access)
        uses: appleboy/ssh-action@master
        with:
          host: ssh.mailtest.live
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          proxy_command: ${{ secrets.CLOUDFLARE_SSH_PROXY }}
          script: |
            cd ~/k8s/salesapp
            git pull
            kubectl rollout restart deployment salesapp
